services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    env_file:
      - ./.env
    ports:
      - 6379:6379

  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
